package com.mealspire.app;

import android.app.Activity;
import android.app.AlertDialog;
import android.graphics.Color;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.text.TextUtils;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import com.mealspire.app.domain.AppSettings;
import com.mealspire.app.domain.Cookbook;
import com.mealspire.app.domain.CookbookEntry;
import com.mealspire.app.domain.CookbookStore;
import com.mealspire.app.domain.DataManager;
import com.mealspire.app.domain.KnownDishImporter;
import com.mealspire.app.domain.KnownDishPromptBuilder;
import com.mealspire.app.domain.IngredientExtractor;
import com.mealspire.app.domain.MealPoolBuilder;
import com.mealspire.app.domain.PortionSize;
import com.mealspire.app.domain.MealHistory;
import com.mealspire.app.domain.MealHistoryStore;
import com.mealspire.app.domain.PreferenceStore;
import com.mealspire.app.domain.Recipe;
import com.mealspire.app.domain.RecipePromptBuilder;
import com.mealspire.app.domain.RecipeRequest;
import com.mealspire.app.domain.RecipeService;
import com.mealspire.app.domain.RecipeTextParser;
import com.mealspire.app.domain.StaleMealSelector;
import com.mealspire.app.domain.UserPreferences;
import com.mealspire.app.net.HttpClaudeClient;
import com.mealspire.app.net.HttpPageFetcher;
import com.mealspire.app.storage.SharedPreferencesAppSettings;
import com.mealspire.app.storage.SharedPreferencesCookbookStore;
import com.mealspire.app.storage.SharedPreferencesMealHistoryStore;
import com.mealspire.app.storage.SharedPreferencesPreferenceStore;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

/**
 * Thin UI layer. One screen, one main action: "Wygeneruj danie". When an API
 * key is configured the dish is generated by the AI — which may either reuse a
 * dish the user has saved or invent a new one — otherwise it falls back to an
 * offline pick from the built-in recipes and the user's cookbook. Secondary
 * actions live behind a single "Więcej…" menu to keep the screen uncluttered.
 */
public class MainActivity extends Activity {
    private static final String[] MEAL_TYPES = {"Śniadanie", "Obiad", "Kolacja"};
    private static final String[] PORTIONS =
            {"1 osoba", "2 osoby", "3 osoby", "4 osoby", "5 osób", "6 osób"};

    private static final Recipe[][] RECIPES = {
            {
                    new Recipe("Owsianka z jabłkiem",
                            "Składniki: płatki owsiane, mleko, jabłko, cynamon, orzechy.\n\n" +
                                    "Gotuj płatki w mleku przez kilka minut. Dodaj starte jabłko, cynamon i orzechy."),
                    new Recipe("Jajecznica ze szczypiorkiem",
                            "Składniki: jajka, masło, szczypiorek, sól, pieprz.\n\n" +
                                    "Rozpuść masło, wlej roztrzepane jajka i mieszaj do ścięcia. Posyp szczypiorkiem."),
                    new Recipe("Tost z awokado",
                            "Składniki: pieczywo, awokado, sok z cytryny, sól, płatki chili.\n\n" +
                                    "Podpiecz pieczywo. Rozgnieć awokado z cytryną i przyprawami, rozsmaruj na toście.")
            },
            {
                    new Recipe("Makaron z pomidorami",
                            "Składniki: makaron, passata, czosnek, oliwa, bazylia.\n\n" +
                                    "Ugotuj makaron. Podsmaż czosnek na oliwie, dodaj passatę i bazylię, połącz z makaronem."),
                    new Recipe("Ryż z warzywami",
                            "Składniki: ryż, marchew, papryka, groszek, sos sojowy.\n\n" +
                                    "Ugotuj ryż. Podsmaż warzywa, dopraw sosem sojowym i wymieszaj z ryżem."),
                    new Recipe("Kurczak z kaszą",
                            "Składniki: pierś z kurczaka, kasza, ogórek, jogurt, koperek.\n\n" +
                                    "Usmaż lub upiecz kurczaka. Podaj z kaszą i szybkim sosem jogurtowo-koperkowym.")
            },
            {
                    new Recipe("Sałatka grecka",
                            "Składniki: pomidor, ogórek, feta, oliwki, oliwa, oregano.\n\n" +
                                    "Pokrój warzywa i fetę. Dodaj oliwki, oliwę oraz oregano, delikatnie wymieszaj."),
                    new Recipe("Kanapki z twarożkiem",
                            "Składniki: pieczywo, twaróg, jogurt, rzodkiewka, szczypiorek.\n\n" +
                                    "Wymieszaj twaróg z jogurtem i warzywami. Nałóż na pieczywo."),
                    new Recipe("Omlet warzywny",
                            "Składniki: jajka, papryka, cebula, szpinak, ser.\n\n" +
                                    "Podsmaż warzywa, zalej jajkami i smaż na małym ogniu. Na koniec dodaj ser.")
            }
    };

    private final Random random = new Random();
    private Spinner mealSpinner;
    private Spinner portionSpinner;
    private TextView recipeTitle;
    private TextView recipeDetails;
    private Button generateButton;
    private Button likeButton;
    private Button dislikeButton;

    private HttpClaudeClient claudeClient;
    private RecipeService recipeService;
    private PreferenceStore preferenceStore;
    private UserPreferences preferences;
    private MealHistoryStore historyStore;
    private MealHistory history;
    private CookbookStore cookbookStore;
    private Cookbook cookbook;
    private KnownDishImporter dishImporter;
    private DataManager dataManager;
    private AppSettings appSettings;
    private final StaleMealSelector staleSelector = new StaleMealSelector();
    private final MealPoolBuilder mealPoolBuilder = new MealPoolBuilder();
    private final IngredientExtractor ingredientExtractor = new IngredientExtractor();
    private Recipe currentRecipe;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        claudeClient = new HttpClaudeClient(BuildConfig.ANTHROPIC_API_KEY);
        recipeService = new RecipeService(claudeClient, new RecipePromptBuilder(),
                new RecipeTextParser());
        preferenceStore = new SharedPreferencesPreferenceStore(this);
        preferences = preferenceStore.load();
        historyStore = new SharedPreferencesMealHistoryStore(this);
        history = historyStore.load();
        cookbookStore = new SharedPreferencesCookbookStore(this);
        cookbook = cookbookStore.load();
        dishImporter = new KnownDishImporter(claudeClient, new HttpPageFetcher(),
                new KnownDishPromptBuilder(), new RecipeTextParser());
        dataManager = new DataManager(preferenceStore, historyStore, cookbookStore);
        appSettings = new SharedPreferencesAppSettings(this);

        ScrollView scrollView = new ScrollView(this);
        scrollView.setBackgroundColor(Color.rgb(255, 247, 237));

        LinearLayout root = new LinearLayout(this);
        root.setOrientation(LinearLayout.VERTICAL);
        root.setPadding(dp(24), dp(32), dp(24), dp(32));
        scrollView.addView(root);

        TextView title = new TextView(this);
        title.setText("Mealspire");
        title.setTextSize(34);
        title.setTextColor(Color.rgb(67, 56, 45));
        title.setGravity(Gravity.CENTER_HORIZONTAL);
        root.addView(title, matchWrap());

        TextView subtitle = new TextView(this);
        subtitle.setText("Wybierz porę dnia i dla ilu osób — resztę wymyśli aplikacja.");
        subtitle.setTextSize(16);
        subtitle.setTextColor(Color.rgb(92, 78, 62));
        subtitle.setGravity(Gravity.CENTER_HORIZONTAL);
        root.addView(subtitle, marginTop(8));

        mealSpinner = new Spinner(this);
        mealSpinner.setId(R.id.meal_spinner);
        mealSpinner.setAdapter(new ArrayAdapter<>(this,
                android.R.layout.simple_spinner_dropdown_item, MEAL_TYPES));
        root.addView(mealSpinner, marginTop(28));

        TextView portionLabel = new TextView(this);
        portionLabel.setText("Dla ilu osób?");
        portionLabel.setTextSize(16);
        portionLabel.setTextColor(Color.rgb(92, 78, 62));
        root.addView(portionLabel, marginTop(16));

        portionSpinner = new Spinner(this);
        portionSpinner.setId(R.id.portion_spinner);
        portionSpinner.setAdapter(new ArrayAdapter<>(this,
                android.R.layout.simple_spinner_dropdown_item, PORTIONS));
        // Restore the remembered number of people (position = servings - 1).
        int rememberedServings = appSettings.loadDefaultServings();
        portionSpinner.setSelection(Math.max(0, Math.min(PORTIONS.length - 1,
                rememberedServings - 1)));
        portionSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                appSettings.saveDefaultServings(position + 1);
            }

            @Override
            public void onNothingSelected(AdapterView<?> parent) {
            }
        });
        root.addView(portionSpinner, marginTop(4));

        generateButton = new Button(this);
        generateButton.setId(R.id.generate_button);
        generateButton.setText("Wygeneruj danie");
        generateButton.setAllCaps(false);
        generateButton.setTextSize(20);
        generateButton.setOnClickListener(view -> generateDish());
        root.addView(generateButton, marginTop(24));

        recipeTitle = new TextView(this);
        recipeTitle.setId(R.id.recipe_title);
        recipeTitle.setTextSize(24);
        recipeTitle.setTextColor(Color.rgb(67, 56, 45));
        root.addView(recipeTitle, marginTop(28));

        recipeDetails = new TextView(this);
        recipeDetails.setId(R.id.recipe_details);
        recipeDetails.setTextSize(17);
        recipeDetails.setLineSpacing(dp(4), 1.0f);
        recipeDetails.setTextColor(Color.rgb(80, 68, 54));
        root.addView(recipeDetails, marginTop(12));

        LinearLayout feedbackRow = new LinearLayout(this);
        feedbackRow.setOrientation(LinearLayout.HORIZONTAL);
        root.addView(feedbackRow, marginTop(20));

        likeButton = new Button(this);
        likeButton.setId(R.id.like_button);
        likeButton.setText("Lubię to");
        likeButton.setAllCaps(false);
        likeButton.setTextSize(16);
        likeButton.setOnClickListener(view -> rateCurrentRecipe(true));
        feedbackRow.addView(likeButton, equalWidthRowItem());

        dislikeButton = new Button(this);
        dislikeButton.setId(R.id.dislike_button);
        dislikeButton.setText("Nie dla mnie");
        dislikeButton.setAllCaps(false);
        dislikeButton.setTextSize(16);
        dislikeButton.setOnClickListener(view -> rateCurrentRecipe(false));
        feedbackRow.addView(dislikeButton, equalWidthRowItem());

        Button moreButton = new Button(this);
        moreButton.setId(R.id.more_button);
        moreButton.setText("Więcej…");
        moreButton.setAllCaps(false);
        moreButton.setTextSize(16);
        moreButton.setOnClickListener(view -> showMoreMenu());
        root.addView(moreButton, marginTop(20));

        setContentView(scrollView);
        showRandomRecipe();
    }

    /** Single entry point for the main action: AI when possible, offline otherwise. */
    private void generateDish() {
        if (claudeClient.hasApiKey()) {
            generateAiRecipe();
        } else {
            showRandomRecipe();
        }
    }

    private void showMoreMenu() {
        boolean hasDish = currentRecipe != null && !currentRecipe.getTitle().trim().isEmpty();
        final List<String> labels = new ArrayList<>();
        final List<Runnable> actions = new ArrayList<>();
        if (hasDish) {
            labels.add("Zapisz danie do mojej bazy");
            actions.add(this::saveCurrentToCookbook);
            labels.add("Lista zakupów");
            actions.add(this::showShoppingList);
        }
        labels.add("Dodaj danie, które znasz i lubisz");
        actions.add(this::showAddKnownDishDialog);
        labels.add("Zarządzaj moimi danymi");
        actions.add(this::showManageDialog);

        new AlertDialog.Builder(this)
                .setTitle("Więcej")
                .setItems(labels.toArray(new String[0]),
                        (dialog, which) -> actions.get(which).run())
                .show();
    }

    private void showAddKnownDishDialog() {
        if (!claudeClient.hasApiKey()) {
            Toast.makeText(this, "Dodawanie z linku/opisu wymaga klucza API.",
                    Toast.LENGTH_LONG).show();
            return;
        }
        final EditText field = new EditText(this);
        field.setHint("Wklej link do przepisu albo opisz danie");
        field.setTextSize(16);
        new AlertDialog.Builder(this)
                .setTitle("Dodaj danie, które znasz")
                .setView(field)
                .setPositiveButton("Dodaj", (dialog, which) ->
                        importKnownDish(field.getText().toString().trim()))
                .setNegativeButton("Anuluj", null)
                .show();
    }

    private void importKnownDish(final String input) {
        if (TextUtils.isEmpty(input)) {
            Toast.makeText(this, "Wklej link albo opisz danie.", Toast.LENGTH_SHORT).show();
            return;
        }

        recipeTitle.setText("Dodaję do bazy…");
        recipeDetails.setText("");

        new Thread(() -> {
            try {
                final CookbookEntry entry = dishImporter.importDish(input);
                runOnUiThread(() -> {
                    cookbook = cookbook.add(entry);
                    cookbookStore.save(cookbook);
                    preferences = preferences.withLike(entry.getTitle());
                    preferenceStore.save(preferences);
                    showRecipe(entry.toRecipe());
                    Toast.makeText(MainActivity.this,
                            "Dodano do bazy: " + entry.getTitle(), Toast.LENGTH_SHORT).show();
                });
            } catch (IOException e) {
                final String message = e.getMessage();
                runOnUiThread(() -> {
                    recipeTitle.setText("Nie udało się dodać dania");
                    recipeDetails.setText(message != null ? message : "Spróbuj ponownie.");
                });
            }
        }).start();
    }

    private void showRandomRecipe() {
        int mealIndex = mealSpinner.getSelectedItemPosition();
        // Pool = built-in recipes for this meal + the user's cookbook, with
        // disliked dishes excluded. Shuffle so ties vary, then prefer the dish
        // not seen for the longest time.
        List<Recipe> pool = mealPoolBuilder.build(RECIPES[mealIndex], cookbook, preferences);
        Collections.shuffle(pool, random);

        List<String> titles = new ArrayList<>();
        for (Recipe recipe : pool) {
            titles.add(recipe.getTitle());
        }
        String stalest = staleSelector.pickStalest(titles, history);

        Recipe chosen = pool.get(0);
        for (Recipe recipe : pool) {
            if (recipe.getTitle().equals(stalest)) {
                chosen = recipe;
                break;
            }
        }
        showRecipe(chosen);
        recordChosen(chosen);
    }

    private void generateAiRecipe() {
        final String mealType = MEAL_TYPES[mealSpinner.getSelectedItemPosition()];
        generateButton.setEnabled(false);
        recipeTitle.setText("Wymyślam danie…");
        recipeDetails.setText("");

        List<String> fragments = new ArrayList<>();
        String portionFragment = PortionSize.promptFragment(
                portionSpinner.getSelectedItemPosition() + 1);
        if (!portionFragment.isEmpty()) {
            fragments.add(portionFragment);
        }

        List<String> knownDishes = cookbook.titles();
        if (knownDishes.size() > 10) {
            knownDishes = knownDishes.subList(0, 10);
        }
        final RecipeRequest request = new RecipeRequest(
                mealType, preferences, history.recentTitles(5), fragments, knownDishes);
        new Thread(() -> {
            try {
                final Recipe recipe = recipeService.generateRecipe(request);
                runOnUiThread(() -> {
                    showRecipe(recipe);
                    recordChosen(recipe);
                    generateButton.setEnabled(true);
                });
            } catch (IOException e) {
                final String message = e.getMessage();
                runOnUiThread(() -> {
                    recipeTitle.setText("Nie udało się wymyślić dania");
                    recipeDetails.setText(message != null ? message
                            : "Spróbuj ponownie za chwilę.");
                    generateButton.setEnabled(true);
                });
            }
        }).start();
    }

    private void showRecipe(Recipe recipe) {
        currentRecipe = recipe;
        recipeTitle.setText(recipe.getTitle());
        recipeDetails.setText(recipe.getDetails());
        boolean hasDish = !recipe.getTitle().trim().isEmpty();
        likeButton.setEnabled(hasDish);
        dislikeButton.setEnabled(hasDish);
    }

    private void showManageDialog() {
        final String[] options = {
                "Pokaż i usuń dania z bazy",
                "Wyczyść preferencje (lubię / nie lubię)",
                "Wyczyść historię podpowiedzi",
                "Wyczyść całą bazę dań"
        };
        new AlertDialog.Builder(this)
                .setTitle("Moje dane")
                .setItems(options, (dialog, which) -> {
                    switch (which) {
                        case 0:
                            showCookbookDialog();
                            break;
                        case 1:
                            dataManager.clearPreferences();
                            preferences = UserPreferences.empty();
                            toast("Wyczyszczono preferencje.");
                            break;
                        case 2:
                            dataManager.clearHistory();
                            history = MealHistory.empty();
                            toast("Wyczyszczono historię.");
                            break;
                        case 3:
                            dataManager.clearCookbook();
                            cookbook = Cookbook.empty();
                            toast("Wyczyszczono bazę dań.");
                            break;
                        default:
                            break;
                    }
                })
                .show();
    }

    private void showCookbookDialog() {
        final String[] titles = cookbook.titles().toArray(new String[0]);
        if (titles.length == 0) {
            toast("Twoja baza jest pusta.");
            return;
        }
        new AlertDialog.Builder(this)
                .setTitle("Dotknij danie, aby je usunąć")
                .setItems(titles, (dialog, which) -> {
                    cookbook = dataManager.removeDish(titles[which]);
                    toast("Usunięto z bazy: " + titles[which]);
                })
                .show();
    }

    private void toast(String message) {
        Toast.makeText(this, message, Toast.LENGTH_SHORT).show();
    }

    private void showShoppingList() {
        if (currentRecipe == null) {
            return;
        }
        List<String> items = ingredientExtractor.extract(currentRecipe.getDetails());
        if (items.isEmpty()) {
            Toast.makeText(this, "Nie znalazłam listy składników w tym przepisie.",
                    Toast.LENGTH_SHORT).show();
            return;
        }
        String[] itemsArray = items.toArray(new String[0]);
        boolean[] checked = new boolean[itemsArray.length];
        new AlertDialog.Builder(this)
                .setTitle("Lista zakupów")
                .setMultiChoiceItems(itemsArray, checked, (dialog, which, isChecked) ->
                        checked[which] = isChecked)
                .setPositiveButton("Gotowe", null)
                .show();
    }

    private void saveCurrentToCookbook() {
        if (currentRecipe == null || currentRecipe.getTitle().trim().isEmpty()) {
            return;
        }
        cookbook = cookbook.add(new CookbookEntry(
                currentRecipe.getTitle(), currentRecipe.getDetails(), "zapisane"));
        cookbookStore.save(cookbook);
        Toast.makeText(this, "Zapisano w bazie: " + currentRecipe.getTitle(),
                Toast.LENGTH_SHORT).show();
    }

    private void recordChosen(Recipe recipe) {
        if (recipe == null || recipe.getTitle().trim().isEmpty()) {
            return;
        }
        history = history.record(recipe.getTitle(), System.currentTimeMillis());
        historyStore.save(history);
    }

    private void rateCurrentRecipe(boolean liked) {
        if (currentRecipe == null || currentRecipe.getTitle().trim().isEmpty()) {
            return;
        }
        String dish = currentRecipe.getTitle();
        preferences = liked ? preferences.withLike(dish) : preferences.withDislike(dish);
        preferenceStore.save(preferences);
        String message = liked
                ? "Zapamiętano, że lubisz: " + dish
                : "Zapamiętano, że unikasz: " + dish;
        Toast.makeText(this, message, Toast.LENGTH_SHORT).show();
    }

    private LinearLayout.LayoutParams equalWidthRowItem() {
        LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(
                0, ViewGroup.LayoutParams.WRAP_CONTENT, 1f);
        params.leftMargin = dp(4);
        params.rightMargin = dp(4);
        return params;
    }

    private LinearLayout.LayoutParams matchWrap() {
        return new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.WRAP_CONTENT
        );
    }

    private LinearLayout.LayoutParams marginTop(int topDp) {
        LinearLayout.LayoutParams params = matchWrap();
        params.topMargin = dp(topDp);
        return params;
    }

    private int dp(int value) {
        return (int) (value * getResources().getDisplayMetrics().density + 0.5f);
    }
}
